/**
 * Naomika Design Studio - Master Admin Console & Inventory Engine
 * Features:
 *   - 3 Photos per product (Main, Side View, Close-Up/Fabric)
 *   - Drag & Drop multi-photo uploader (WhatsApp, Desktop, Camera)
 *   - Live 2-column layout (Add/Edit on Left, Live Inventory on Right)
 *   - Direct write-back to products.xlsx, data/products.json, data/products.js
 *   - One-click "Publish Online" (auto-sync & commit)
 *   - One-click "Pull Latest Updates" from GitHub for seamless co-worker collaboration
 */

const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const XLSX = require('xlsx');
const { exec, execSync } = require('child_process');

const app = express();
const PORT = process.env.PORT || 3000;
const BASE_DIR = __dirname;
const XLSX_FILE = path.join(BASE_DIR, 'products.xlsx');
const DATA_JSON = path.join(BASE_DIR, 'data', 'products.json');
const DATA_JS = path.join(BASE_DIR, 'data', 'products.js');
const IMAGES_DIR = path.join(BASE_DIR, 'images');

app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));
app.use(express.static(BASE_DIR));

// Setup Multer for up to 3+ photos upload
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    if (!fs.existsSync(IMAGES_DIR)) fs.mkdirSync(IMAGES_DIR, { recursive: true });
    cb(null, IMAGES_DIR);
  },
  filename: function (req, file, cb) {
    const ext = path.extname(file.originalname) || '.jpg';
    const base = path.basename(file.originalname, ext).replace(/[^a-zA-Z0-9_-]/g, '_');
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E4);
    cb(null, `${base}_${uniqueSuffix}${ext}`);
  }
});
const upload = multer({ storage: storage });

// Read products
function getProducts() {
  if (fs.existsSync(DATA_JSON)) {
    try {
      return JSON.parse(fs.readFileSync(DATA_JSON, 'utf8'));
    } catch (e) {
      console.error('Error reading JSON:', e);
    }
  }
  return [];
}

// Save products to JSON, JS, and XLSX with 3 images per product
function saveProducts(products) {
  if (!fs.existsSync(path.join(BASE_DIR, 'data'))) {
    fs.mkdirSync(path.join(BASE_DIR, 'data'), { recursive: true });
  }

  // 1. JSON
  fs.writeFileSync(DATA_JSON, JSON.stringify(products, null, 2), 'utf8');

  // 2. JS
  const jsContent = `/**
 * Auto-generated by Naomika Design Studio Engine
 * Updated: ${new Date().toISOString()}
 * Total Products: ${products.length}
 */
window.STUDIO_PRODUCTS = ${JSON.stringify(products, null, 2)};
`;
  fs.writeFileSync(DATA_JS, jsContent, 'utf8');

  // 3. Excel (Supports 3 Photos)
  try {
    const excelRows = products.map((p, idx) => {
      const imgs = Array.isArray(p.images) && p.images.length > 0 ? p.images : [p.image || 'images/1.jpeg'];
      return {
        'Product Code': p.code,
        'Product Name': p.name,
        'Category': p.category,
        'Price': p.price,
        'Original Price': p.originalPrice || 0,
        'Image 1': (imgs[0] || p.image || '').replace(/^images\//, ''),
        'Image 2': (imgs[1] || p.image2 || '').replace(/^images\//, ''),
        'Image 3': (imgs[2] || p.image3 || '').replace(/^images\//, ''),
        'Stock Status': p.stockStatus || 'In Stock',
        'Badge': p.badge || 'Fresh Arrivals',
        'Description': p.description || '',
        'Featured': p.featured ? 'Yes' : 'No'
      };
    });

    const ws = XLSX.utils.json_to_sheet(excelRows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Naomika Catalog');
    XLSX.writeFile(wb, XLSX_FILE);
  } catch (e) {
    console.error('Error writing Excel file:', e);
  }
}

// Admin UI Route
app.get(['/admin', '/admin.html'], (req, res) => {
  res.sendFile(path.join(BASE_DIR, 'admin.html'));
});

// API: Get products
app.get('/api/products', (req, res) => {
  res.json({ success: true, products: getProducts() });
});

// API: Upload up to 3 images via Drag & Drop (WhatsApp / Desktop / File input)
app.post('/api/upload', upload.array('imageFiles', 10), (req, res) => {
  if (!req.files || req.files.length === 0) {
    return res.status(400).json({ success: false, error: 'No images received' });
  }
  const uploadedPaths = req.files.map(f => `images/${f.filename}`);
  res.json({
    success: true,
    imagePaths: uploadedPaths,
    imagePath: uploadedPaths[0],
    filenames: req.files.map(f => f.filename)
  });
});

// API: Add or Update Product (Supports 3 Photos)
app.post('/api/products', (req, res) => {
  const item = req.body;
  if (!item || !item.code) {
    return res.status(400).json({ success: false, error: 'Product Code is required' });
  }

  let products = getProducts();
  const code = String(item.code).trim().toUpperCase();
  const index = products.findIndex(p => p.code.toUpperCase() === code);

  const price = parseFloat(item.price) || 0;
  const origPrice = parseFloat(item.originalPrice) || 0;

  // Handle 3 Photos
  let images = [];
  if (Array.isArray(item.images) && item.images.length > 0) {
    images = item.images.map(img => img.startsWith('images/') ? img : `images/${img}`);
  } else if (item.image) {
    images.push(item.image.startsWith('images/') ? item.image : `images/${item.image}`);
    if (item.image2) images.push(item.image2.startsWith('images/') ? item.image2 : `images/${item.image2}`);
    if (item.image3) images.push(item.image3.startsWith('images/') ? item.image3 : `images/${item.image3}`);
  }
  if (images.length === 0) images = ['images/1.jpeg'];

  const productData = {
    id: index >= 0 ? products[index].id : products.length + 1,
    code: code,
    name: item.name || 'Untitled Creation',
    category: item.category || 'Ladies Wear',
    subcategory: item.subcategory || 'Designer Wear',
    price: price,
    priceDisplay: price > 0 ? `₹${price.toLocaleString('en-IN')}` : 'Bespoke / On Request',
    originalPrice: origPrice,
    originalPriceDisplay: origPrice > 0 ? `₹${origPrice.toLocaleString('en-IN')}` : '',
    image: images[0],
    image2: images[1] || images[0],
    image3: images[2] || images[0],
    images: images,
    stockStatus: item.stockStatus || 'In Stock',
    badge: item.badge || 'Fresh Arrivals',
    tagline: item.badge || 'Fresh Arrivals',
    description: item.description || 'Handcrafted designer creation by Naomika Design Studio.',
    featured: Boolean(item.featured)
  };

  if (index >= 0) {
    products[index] = productData;
  } else {
    // New products are added to the beginning so they appear at the top of Fresh Arrivals!
    products.unshift(productData);
  }

  saveProducts(products);
  res.json({
    success: true,
    message: `Product ${code} successfully saved with ${images.length} photos!`,
    product: productData,
    total: products.length
  });
});

// API: Delete Product
app.delete('/api/products/:code', (req, res) => {
  const code = req.params.code.trim().toUpperCase();
  let products = getProducts();
  const filtered = products.filter(p => p.code.toUpperCase() !== code);

  if (filtered.length === products.length) {
    return res.status(404).json({ success: false, error: 'Product not found' });
  }

  saveProducts(filtered);
  res.json({ success: true, message: `Product ${code} deleted from products.xlsx`, remaining: filtered.length });
});

// API: Pull Latest Updates from Git repository for co-worker collaboration
app.all('/api/pull', (req, res) => {
  exec('git --version', (gitCheckErr) => {
    if (gitCheckErr) {
      return res.json({ success: false, error: 'Git not found on this machine. Please install Git.' });
    }
    const gitDir = path.join(BASE_DIR, '.git');
    if (!fs.existsSync(gitDir)) {
      try {
        execSync('git init', { cwd: BASE_DIR });
      } catch (e) {}
      return res.json({
        success: true,
        output: 'Git repository initialized. Add your GitHub remote URL to pull shared commits.'
      });
    }

    exec('git pull origin main', { cwd: BASE_DIR }, (err, stdout, stderr) => {
      exec('node sync_store.js', { cwd: BASE_DIR });
      if (err) {
        return res.json({ success: false, error: stderr || err.message, output: stdout });
      }
      res.json({ success: true, output: stdout || 'Latest updates pulled successfully from GitHub!' });
    });
  });
});

// API: Publish Online (Runs sync_store.js, commits, and updates store)
app.post('/api/publish', (req, res) => {
  exec('node sync_store.js', { cwd: BASE_DIR }, (syncErr, syncOut) => {
    const gitDir = path.join(BASE_DIR, '.git');
    if (!fs.existsSync(gitDir)) {
      try { execSync('git init', { cwd: BASE_DIR }); } catch(e){}
    }
    exec('git add . && git commit -m "Admin Catalog Update" && git push origin main', { cwd: BASE_DIR }, (gitErr, gitOut) => {
      res.json({
        success: true,
        message: 'Store published and synced successfully!',
        output: syncOut + (gitOut ? ('\n' + gitOut) : '')
      });
    });
  });
});

// API: Stats
app.get('/api/stats', (req, res) => {
  const products = getProducts();
  res.json({
    success: true,
    total: products.length,
    ladies: products.filter(p => p.category.toLowerCase() === 'ladies wear').length,
    mens: products.filter(p => p.category.toLowerCase() === 'mens wear').length,
    custom: products.filter(p => p.category.toLowerCase() === 'customization' || p.stockStatus === 'Made to Order').length
  });
});

app.listen(PORT, () => {
  console.log('===================================================');
  console.log(`  Naomika Design Studio - Master Admin Console`);
  console.log(`  -> Storefront: http://localhost:${PORT}`);
  console.log(`  -> Admin:      http://localhost:${PORT}/admin`);
  console.log('===================================================');
});
